services:
  app:
    build: .
    container_name: crmm-banking-container
    command: python app/app.py
    ports:
      - 5000:5000
    volumes:
      - .:/code
  tests:
    build: .
    command: pytest
    depends_on:
      - app
